"""
Package everything for Roblox Studio:

    python3 tools/build_roblox.py

  studio/SetupImportedAssets.luau   <- generated from blender-models/out/*/manifest.json
  studio/INSTALL_SCRIPTS.luau       <- one-paste installer for the Kit / Client / Server scripts
  build/SnowboardKit.rbxm           <- drag into ReplicatedStorage
  build/SnowboardClient.rbxm        <- drag into StarterPlayer > StarterPlayerScripts
  build/SnowboardServer.rbxm        <- drag into ServerScriptService
  sfx/*.ogg                         <- sounds to upload
  textures/*.png                    <- palette + board/sign textures + particle textures
"""

import glob
import json
import os
import shutil
import subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPO = os.path.dirname(ROOT)
MODELS_OUT = os.path.join(REPO, "blender-models", "out")


def lua_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def gen_setup():
    manifests = []
    for path in sorted(glob.glob(os.path.join(MODELS_OUT, "*", "manifest.json"))):
        with open(path) as f:
            manifests.append(json.load(f))
    lines, textures = [], set()
    for m in manifests:
        lines.append(f'\t[{lua_str(m["name"])}] = {{')
        lines.append(f'\t\tcategory = {lua_str(m.get("category", "Props"))},')
        lines.append(f'\t\tcollision = {lua_str(m.get("collision", "Default"))},')
        lines.append("\t\tparts = {")
        for pname, p in m["parts"].items():
            fields = []
            if "material" in p:
                fields.append(f'material = {lua_str(p["material"])}')
                fields.append("color = { %d, %d, %d }" % tuple(p["color"]))
            if "texture" in p:
                fields.append(f'texture = {lua_str(p["texture"])}')
                if p["texture"] != "palette.png":
                    textures.add(p["texture"])
            lines.append(f'\t\t\t[{lua_str(pname)}] = {{ {", ".join(fields)} }},')
        lines.append("\t\t},")
        lines.append("\t},")
    tex_lines = [f"\t[{lua_str(t)}] = \"\"," for t in sorted(textures)]
    with open(os.path.join(ROOT, "tools", "SetupImportedAssets.template.luau")) as f:
        tpl = f.read()
    out = tpl.replace("__MANIFEST__", "\n".join(lines)).replace("__TEXTURE_KEYS__", "\n".join(tex_lines))
    dst = os.path.join(ROOT, "studio", "SetupImportedAssets.luau")
    with open(dst, "w") as f:
        f.write(out)
    return len(manifests), sorted(textures)


def long_string(src):
    n = 1
    while ("]" + "=" * n + "]") in src:
        n += 1
    return "[" + "=" * n + "[\n" + src + "]" + "=" * n + "]"


def gen_installer():
    items = []  # (container expr, class, name, source)

    def add(container, cls, name, path):
        with open(path) as f:
            items.append((container, cls, name, f.read()))

    for p in sorted(glob.glob(os.path.join(ROOT, "src", "shared", "*.luau"))):
        add("kit", "ModuleScript", os.path.basename(p)[:-5], p)
    add("starterScripts", "LocalScript", "SnowboardClient", os.path.join(ROOT, "src", "client", "init.client.luau"))
    for p in sorted(glob.glob(os.path.join(ROOT, "src", "client", "*.luau"))):
        if not os.path.basename(p).startswith("init"):
            add("client", "ModuleScript", os.path.basename(p)[:-5], p)
    add("serverScripts", "Script", "SnowboardServer", os.path.join(ROOT, "src", "server", "init.server.luau"))
    for p in sorted(glob.glob(os.path.join(ROOT, "src", "server", "*.luau"))):
        if not os.path.basename(p).startswith("init"):
            add("server", "ModuleScript", os.path.basename(p)[:-5], p)

    out = ["--!strict",
           "-- INSTALL_SCRIPTS  (paste into the Studio Command Bar and press Enter)",
           "-- Creates / updates ReplicatedStorage.SnowboardKit, StarterPlayerScripts.SnowboardClient and",
           "-- ServerScriptService.SnowboardServer. Your Config (asset ids) is kept unless OVERWRITE_CONFIG = true.",
           "-- Generated by roblox/tools/build_roblox.py - edit the files in roblox/src instead.",
           "",
           "local OVERWRITE_CONFIG = false",
           "",
           "local RS = game:GetService(\"ReplicatedStorage\")",
           "local SSS = game:GetService(\"ServerScriptService\")",
           "local SPS = game:GetService(\"StarterPlayer\"):WaitForChild(\"StarterPlayerScripts\")",
           "local recording = game:GetService(\"ChangeHistoryService\"):TryBeginRecording(\"InstallSnowboardKit\")",
           "",
           "local function ensure(parent: Instance, className: string, name: string): Instance",
           "\tlocal found = parent:FindFirstChild(name)",
           "\tif found and found.ClassName == className then",
           "\t\treturn found",
           "\tend",
           "\tif found then",
           "\t\tfound:Destroy()",
           "\tend",
           "\tlocal inst = Instance.new(className :: any)",
           "\tinst.Name = name",
           "\tinst.Parent = parent",
           "\treturn inst",
           "end",
           "",
           "local function write(parent: Instance, className: string, name: string, source: string)",
           "\tif name == \"Config\" and parent:FindFirstChild(\"Config\") and not OVERWRITE_CONFIG then",
           "\t\treturn parent:FindFirstChild(\"Config\") :: Instance",
           "\tend",
           "\tlocal s = ensure(parent, className, name);",
           "\t(s :: any).Source = source",
           "\treturn s",
           "end",
           "",
           "local kit = ensure(RS, \"Folder\", \"SnowboardKit\")",
           "local starterScripts = SPS",
           "local serverScripts = SSS",
           "local client: Instance, server: Instance",
           ""]
    for container, cls, name, src in items:
        lhs = ""
        if cls == "LocalScript":
            lhs = "client = "
        elif cls == "Script":
            lhs = "server = "
        out.append(f"{lhs}write({container}, {lua_str(cls)}, {lua_str(name)}, {long_string(src)})")
        out.append("")
    out += ["if recording then",
            "\tgame:GetService(\"ChangeHistoryService\"):FinishRecording(recording, Enum.FinishRecordingOperation.Commit)",
            "end",
            f"print(\"[SnowboardKit] installed {len(items)} scripts\")", ""]
    dst = os.path.join(ROOT, "studio", "INSTALL_SCRIPTS.luau")
    with open(dst, "w") as f:
        f.write("\n".join(out))
    return len(items)


def rojo_build():
    rojo = shutil.which("rojo") or os.path.expanduser("~/bin/rojo")
    os.makedirs(os.path.join(ROOT, "build"), exist_ok=True)
    built = []
    for proj, name in (("kit", "SnowboardKit"), ("client", "SnowboardClient"), ("server", "SnowboardServer")):
        out = os.path.join(ROOT, "build", name + ".rbxm")
        subprocess.run([rojo, "build", f"{proj}.project.json", "-o", out], cwd=ROOT, check=True,
                       stdout=subprocess.DEVNULL)
        built.append(os.path.relpath(out, ROOT))
    return built


def copy_assets():
    sfx_src = os.path.join(REPO, "blender-models", "sfx", "out")
    sfx_dst = os.path.join(ROOT, "sfx")
    os.makedirs(sfx_dst, exist_ok=True)
    n = 0
    for p in glob.glob(os.path.join(sfx_src, "*.ogg")):
        shutil.copy(p, sfx_dst)
        n += 1
    tex_dst = os.path.join(ROOT, "textures")
    os.makedirs(tex_dst, exist_ok=True)
    for p in glob.glob(os.path.join(REPO, "blender-models", "textures", "*.png")):
        shutil.copy(p, tex_dst)
    pal = glob.glob(os.path.join(MODELS_OUT, "*", "palette.png"))
    if pal:
        shutil.copy(pal[0], os.path.join(tex_dst, "palette.png"))
    return n


if __name__ == "__main__":
    n_models, textures = gen_setup()
    print(f"SetupImportedAssets.luau: {n_models} models, {len(textures)} extra textures")
    print(f"INSTALL_SCRIPTS.luau: {gen_installer()} scripts")
    print("rbxm:", ", ".join(rojo_build()))
    print(f"copied {copy_assets()} sounds + textures")
